import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Read the linter report from linter-report.txt
 * @param {string} reportPath - Path to the linter report file
 * @returns {string} - The content of the report file
 */
function readLinterReport(reportPath) {
    if (!fs.existsSync(reportPath)) {
        throw new Error(`Linter report not found at: ${reportPath}`);
    }
    return fs.readFileSync(reportPath, 'utf8');
}

/**
 * Create a comment on a GitHub Pull Request
 * DOCS: https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment
 * Note: GitHub treats PR comments as issue comments
 * 
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @param {number} prNumber - Pull request number
 * @param {string} body - Comment body
 * @param {string} githubToken - GitHub authentication token
 * @returns {Promise<object>} - The created comment response
 */
async function createPRComment(owner, repo, prNumber, body, githubToken) {
    const token = githubToken || process.env.GITHUB_TOKEN;
    
    if (!token) {
        throw new Error('GitHub token is required. Set GITHUB_TOKEN environment variable.');
    }
    
    try {
        const response = await fetch(
            `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`,
            {
                method: 'POST',
                headers: {
                    'Accept': 'application/vnd.github+json',
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json',
                    'X-GitHub-Api-Version': '2022-11-28'
                },
                body: JSON.stringify({
                    body: body
                })
            }
        );

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Failed to create PR comment: ${response.status} - ${errorText}`);
        }

        return await response.json();
    } catch (error) {
        console.error('Error creating PR comment:', error);
        throw error;
    }
}

/**
 * Format the linter report as a GitHub markdown comment
 * @param {string} reportContent - Raw linter report content
 * @returns {string} - Formatted markdown comment
 */
function formatReportAsMarkdown(reportContent) {
    return `## 🔍 Linter Report

<details>
<summary>Click to expand full report</summary>

\`\`\`
${reportContent}
\`\`\`

</details>

---
*This comment was automatically generated by the linter bot.*`;
}

/**
 * Resolve PR number from PR_ID env var or PR_NUMBER_PATH file.
 * The file-based approach supports workflow_run triggers where PR context
 * is passed via artifact instead of the event payload.
 * @returns {string} PR number
 */
function resolvePRNumber() {
    if (process.env.PR_ID) {
        return process.env.PR_ID.trim();
    }

    const prNumberPath = process.env.PR_NUMBER_PATH;
    if (prNumberPath && fs.existsSync(prNumberPath)) {
        const prNumber = fs.readFileSync(prNumberPath, 'utf8').trim();
        if (prNumber) return prNumber;
    }

    console.error('❌ Error: PR number is required. Set PR_ID env var or PR_NUMBER_PATH pointing to a file containing the PR number.');
    process.exit(1);
}

/**
 * Main execution function
 */
async function main() {
    const githubToken = process.env.GITHUB_TOKEN;
    const githubRepository = process.env.GITHUB_REPOSITORY; // format: owner/repo

    if (!githubToken) {
        console.error('❌ Error: GITHUB_TOKEN environment variable is required');
        process.exit(1);
    }

    if (!githubRepository) {
        console.error('❌ Error: GITHUB_REPOSITORY environment variable is required');
        process.exit(1);
    }

    const prId = resolvePRNumber();

    const [owner, repo] = githubRepository.split('/');
    if (!owner || !repo) {
        console.error('❌ Error: GITHUB_REPOSITORY must be in format "owner/repo"');
        process.exit(1);
    }

    const reportPath = process.env.LINTER_REPORT_PATH || path.join(process.cwd(), 'linter-report.txt');

    console.log('📋 Linter Report Bot');
    console.log('─'.repeat(50));
    console.log(`Repository: ${owner}/${repo}`);
    console.log(`PR Number: ${prId}`);
    console.log(`Report Path: ${reportPath}`);
    console.log('─'.repeat(50));

    try {
        console.log('📖 Reading linter report...');
        const reportContent = readLinterReport(reportPath);
        
        const markdownComment = formatReportAsMarkdown(reportContent);
        
        console.log('📝 Posting comment to PR...');
        const result = await createPRComment(owner, repo, parseInt(prId, 10), markdownComment, githubToken);
        
        console.log('✅ Successfully posted linter report to PR!');
        console.log(`   Comment URL: ${result.html_url}`);
        
    } catch (error) {
        if (error.message.includes('403') && error.message.includes('Resource not accessible')) {
            console.error('❌ Failed to post linter report: GITHUB_TOKEN lacks write permissions.');
            console.error('   For fork PRs, the default GITHUB_TOKEN is read-only.');
            console.error('   Use a workflow_run trigger so the comment step runs in the base repo context.');
            console.error('   See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run');
        } else {
            console.error(`❌ Failed to post linter report: ${error.message}`);
        }
        process.exit(1);
    }
}

// Run main function
main();

// Export functions for testing or reuse
export {
    readLinterReport,
    createPRComment,
    formatReportAsMarkdown,
    resolvePRNumber
};
